In [1]:
import html5lib
import lxml

from bs4 import BeautifulSoup as bs

import requests
import re

import pandas as pd

import os

import time
import random

In [2]:
years = range(2010, 2024)

In [3]:
team_to_url_df = pd.DataFrame(
    data=[
        [
            'crd', #Cardinals
            'atl', #Falcons
            'rav', #Ravens
            'buf', #Bills
            'car', #Panthers
            'chi', #Bears
            'cin', #Bengals
            'cle', #Browns
            'dal', #Cowboys
            'den', #Broncos
            'det', #Lions
            'gnb', #Packers
            'htx', #Texans
            'clt', # Colts
            'jax', #Jaguars
            'kan', #Chiefs
            'rai', #Raiders
            'sdg', #Chargers
            'ram', #Rams
            'mia', #Dolphins
            'min', #Vikings
            'nwe', #Patriots
            'nor', #Saints
            'nyg', #Giants
            'nyj', #Jets
            'phi', #Eagles
            'pit', #Steelers
            'sfo', #49ers
            'sea', #Seahawks
            'tam', #Buccaneers
            'oti', #Titans
            'was' #Commanders
        ]
    ], 
    columns=[
        'Cardinals',
        'Falcons',
        'Ravens',
        'Bills',
        'Panthers',
        'Bears',
        'Bengals',
        'Browns',
        'Cowboys',
        'Broncos',
        'Lions',
        'Packers',
        'Texans',
        'Colts',
        'Jaguars',
        'Chiefs',
        'Raiders',
        'Chargers',
        'Rams',
        'Dolphins',
        'Vikings',
        'Patriots',
        'Saints',
        'Giants',
        'Jets',
        'Eagles',
        'Steelers',
        '49ers',
        'Seahawks',
        'Buccaneers',
        'Titans',
        'Commanders'
    ])

# Import Roster 2010-2023

In [4]:
# use this function before creating tables
def roster_df(url:str):
    
    html_roster_str = requests.get(url).text

    soup = bs(html_roster_str, 'lxml')

    html_roster = soup.find_all('div', class_='table_wrapper')[1]
    
        # index the 5th element to get table
    html_roster_children_li = []
    for hrc in html_roster.children:
        html_roster_children_li.append(hrc)

    df = pd.read_html(html_roster_children_li[4])[0]

    time.sleep(random.randrange(5,8))

    return df

In [5]:
def create_roster_csv(team_url:str, year:int):

    # format team_to_url_df list to choose team, the second bracket is for the year
    roster_url = 'http://www.pro-football-reference.com/teams/{}/{}_roster.htm'
            
    #webscrape roster dataframe
    url = roster_url.format(team_url, year)
    df = roster_df(url=url)
    
    #drop last col
    df = df.drop(columns=['Drafted (tm/rnd/yr)'], axis=1)

    try:
        df = df.drop(columns=['Salary'], axis=1)
    except:
        pass
                         
    return df

In [6]:
def mani_roster(roster_df:pd)->pd:

    #rename columns
    roster_df.columns = ['No.', 'Player', 'Age', 'Position', 'Games_Played_in_Season', 
                  'Games_Started_in_Season', 'Weight', 'Height', 'College/University', 'BirthDate',
                 'NFL_Years', 'Player_Value']

    #change Rook to 0 in yrs column
    roster_df['NFL_Years'] = roster_df['NFL_Years'].replace('Rook', 0)

    #change datataype to integer
    df['NFL_Years'] = df['NFL_Years'].astype('float64')

    roster_df['Team'] = [team] * len(roster_df)
    roster_df['Year'] = [year] * len(roster_df)

    #Reorder clumns
    roster_df = roster_df[['No.', 'Player', 'BirthDate', 'Age', 'Height', 'Weight', 
             'College/University', 'Position', 'Games_Played_in_Season',
            'Games_Started_in_Season', 'NFL_Years', 'Player_Value', 'Team', 'Year']]

    return roster_df

In [7]:
for year in years:
    for team in team_to_url_df.columns:

        team_url = team_to_url_df[team].values[0]
        
        df = create_roster_csv(team_url=team_url, year=year)

        df = mani_roster(roster_df=df)
        
        #where to save datafram
        df.to_csv(f'NFL_Data_{year}\{team}\{team}_roster')
        
        print(df)

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.            Player   BirthDate   Age Height  Weight  \
0   42.0   Andre' Anderson    5/1/1988  22.0   5-11   205.0
1   50.0      Akin Ayodele   9/17/1979  31.0    6-2   245.0
2   94.0      Mike Balogun   9/28/1983  27.0    6-0   240.0
3   77.0    Demetress Bell    5/3/1984  26.0    6-5   301.0
4    4.0       Brian Brohm   9/23/1985  25.0    6-3   227.0
..   ...               ...         ...   ...    ...     ...
64  70.0         Eric Wood   3/18/1986  24.0    6-4   310.0
65  49.0      Pierre Woods    1/6/1982  28.0    6-5   255.0
66  61.0  Mansfield Wrotto  10/12/1984  26.0    6-3   316.0
67  26.0    Ashton Youboty    7/7/1984  26.0    6-0   192.0
68   NaN        Team Total         NaN  26.5  6-2.0   247.4

       College/University Position  Games_Played_in_Season  \
0                  Tulane       RB                       2
1                  Purdue     LILB                      15
2     Lackawanna,Oklahoma       LB                       2
3   Northwestern St. (LA)       LT                      16
4              Louisville       QB                       1
..                    ...      ...                     ...
64             Louisville       RG                      14
65               Michigan       LB                       4
66           Georgia Tech       RT                      11
67               Ohio St.       DB                      13
68                    NaN      NaN                      16

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                       0.0        0.0           0.0  Bills  2010
1                      10.0        8.0           4.0  Bills  2010
2                       0.0        0.0           0.0  Bills  2010
3                      16.0        1.0           6.0  Bills  2010
4                       1.0        1.0           0.0  Bills  2010
..                      ...        ...           ...    ...   ...
64                     14.0        1.0           6.0  Bills  2010
65                      0.0        4.0           0.0  Bills  2010
66                      7.0        2.0           3.0  Bills  2010
67                      0.0        4.0           1.0  Bills  2010
68                      NaN        3.1           NaN  Bills  2010

[69 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.          Player  BirthDate   Age Height  Weight  \
0   88.0     Kamar Aiken  5/30/1989  22.0    6-2   216.0
1   50.0    Nick Barnett  5/27/1981  30.0    6-2   228.0
2   57.0    Danny Batten  12/8/1987  24.0    6-4   250.0
3   77.0  Demetress Bell   5/3/1984  27.0    6-5   301.0
4   87.0     Kevin Brock   4/9/1986  25.0    6-5   315.0
..   ...             ...        ...   ...    ...     ...
61  95.0   Kyle Williams  6/10/1983  28.0    6-1   303.0
62  37.0   George Wilson  3/14/1981  30.0    6-0   210.0
63  70.0       Eric Wood  3/18/1986  25.0    6-4   310.0
64  71.0       Sam Young  6/24/1987  24.0    6-8   302.0
65   NaN      Team Total        NaN  26.6  6-2.3   247.5

       College/University Position  Games_Played_in_Season  \
0         Central Florida       WR                       2
1              Oregon St.     RILB                      16
2        South Dakota St.       LB                      16
3   Northwestern St. (LA)       LT                       7
4                 Rutgers       TE                       2
..                    ...      ...                     ...
61                    LSU       NT                       5
62               Arkansas       SS                      13
63             Louisville        C                       9
64             Notre Dame        T                       4
65                    NaN      NaN                      16

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                       0.0        0.0           0.0  Bills  2011
1                      16.0        8.0           7.0  Bills  2011
2                       4.0        0.0           2.0  Bills  2011
3                       6.0        2.0           3.0  Bills  2011
4                       0.0        0.0           0.0  Bills  2011
..                      ...        ...           ...    ...   ...
61                      5.0        5.0           2.0  Bills  2011
62                     13.0        6.0           5.0  Bills  2011
63                      9.0        2.0           4.0  Bills  2011
64                      0.0        1.0           0.0  Bills  2011
65                      NaN        3.3           NaN  Bills  2011

[66 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.          Player   BirthDate   Age Height  Weight  College/University  \
0   93.0   Mark Anderson   5/26/1983  29.0    6-4   255.0             Alabama
1   50.0    Nick Barnett   5/27/1981  31.0    6-2   228.0          Oregon St.
2   53.0   Nigel Bradham    9/4/1989  23.0    6-2   241.0         Florida St.
3   33.0      Ron Brooks  10/16/1988  24.0   5-10   190.0                 LSU
4   74.0     Colin Brown   8/29/1985  27.0    6-8   325.0            Missouri
..   ...             ...         ...   ...    ...     ...                 ...
60  94.0  Mario Williams   1/31/1985  27.0    6-6   300.0  North Carolina St.
61  37.0   George Wilson   3/14/1981  31.0    6-0   210.0            Arkansas
62  70.0       Eric Wood   3/18/1986  26.0    6-4   310.0          Louisville
63  71.0       Sam Young   6/24/1987  25.0    6-8   302.0          Notre Dame
64   NaN      Team Total         NaN  26.5  6-2.3   247.1                 NaN

   Position  Games_Played_in_Season  Games_Started_in_Season  NFL_Years  \
0        DE                       5                      4.0        6.0
1       RLB                      16                     16.0        9.0
2       LLB                      16                     11.0        0.0
3        DB                       9                      2.0        0.0
4         T                       1                      1.0        1.0
..      ...                     ...                      ...        ...
60      LDE                      16                     16.0        6.0
61       SS                      16                     16.0        7.0
62        C                      14                     14.0        3.0
63        T                      12                      4.0        2.0
64      NaN                      16                      NaN        3.3

    Player_Value   Team  Year
0            2.0  Bills  2012
1            6.0  Bills  2012
2            4.0  Bills  2012
3            1.0  Bills  2012
4            0.0  Bills  2012
..           ...    ...   ...
60           7.0  Bills  2012
61           5.0  Bills  2012
62           6.0  Bills  2012
63           3.0  Bills  2012
64           NaN  Bills  2012

[65 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.         Player   BirthDate   Age Height  Weight College/University  \
0   30.0   Johnny Adams    6/9/1989  24.0   5-10   185.0       Michigan St.
1   50.0    Kiko Alonso   8/14/1990  23.0    6-3   239.0             Oregon
2   62.0     Mark Asper   11/8/1985  28.0    6-6   319.0             Oregon
3   53.0  Nigel Bradham    9/4/1989  24.0    6-2   241.0        Florida St.
4   90.0    Alan Branch  12/29/1984  29.0    6-6   350.0           Michigan
..   ...            ...         ...   ...    ...     ...                ...
60  42.0   Ronnie Wingo   2/18/1991  22.0    6-3   231.0           Arkansas
61  70.0      Eric Wood   3/18/1986  27.0    6-4   310.0         Louisville
62  10.0   Robert Woods   4/10/1992  21.0    6-0   195.0                USC
63  71.0      Sam Young   6/24/1987  26.0    6-8   302.0         Notre Dame
64   NaN     Team Total         NaN  26.1  6-2.1   245.0                NaN

   Position  Games_Played_in_Season  Games_Started_in_Season  NFL_Years  \
0        DB                       4                      0.0        0.0
1       MLB                      16                     16.0        0.0
2         G                       6                      0.0        1.0
3        LB                      16                      2.0        1.0
4       LDE                      16                     13.0        6.0
..      ...                     ...                      ...        ...
60       RB                       2                      0.0        0.0
61        C                      16                     16.0        4.0
62       WR                      14                     14.0        0.0
63        T                       4                      0.0        3.0
64      NaN                      16                      NaN        2.6

    Player_Value   Team  Year
0            0.0  Bills  2013
1           10.0  Bills  2013
2            0.0  Bills  2013
3            2.0  Bills  2013
4            6.0  Bills  2013
..           ...    ...   ...
60           0.0  Bills  2013
61           7.0  Bills  2013
62           5.0  Bills  2013
63           0.0  Bills  2013
64           NaN  Bills  2013

[65 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.                 Player   BirthDate   Age Height  Weight  \
0   53.0          Nigel Bradham    9/4/1989  25.0    6-2   241.0
1   33.0             Ron Brooks  10/16/1988  26.0   5-10   190.0
2   35.0            Bryce Brown   5/14/1991  23.0    6-0   223.0
3   52.0          Preston Brown  10/27/1992  22.0    6-1   251.0
4   97.0          Corbin Bryant    1/4/1988  26.0    6-4   300.0
5    2.0          Dan Carpenter  11/25/1985  29.0    6-2   216.0
6   84.0         Scott Chandler   7/23/1985  29.0    6-7   270.0
7   96.0         Stefan Charles    6/9/1988  26.0    6-5   302.0
8   29.0          Ross Cockrell    8/6/1991  23.0    6-0   191.0
9   99.0         Marcell Dareus   3/13/1990  24.0    6-3   331.0
10  54.0             Larry Dean    8/7/1988  26.0    6-0   216.0
11  26.0          Anthony Dixon   9/24/1987  27.0    6-1   239.0
12  81.0          Marcus Easley   11/2/1987  27.0    6-2   225.0
13   4.0             Jordan Gay   3/29/1990  24.0    6-0   200.0
14  24.0        Stephon Gilmore   9/19/1990  24.0    6-0   190.0
15  77.0            Cordy Glenn   9/18/1989  25.0    6-6   345.0
16  88.0       Marquise Goodwin  11/19/1990  24.0    5-9   185.0
17  89.0            Chris Gragg   6/30/1990  24.0    6-3   244.0
18  20.0           Corey Graham   7/25/1985  29.0    6-0   196.0
19  48.0          MarQueis Gray   11/7/1989  25.0    6-4   263.0
20  75.0         Chris Hairston   4/26/1989  25.0    6-6   323.0
21  66.0     Seantrel Henderson   1/21/1992  22.0    6-7   351.0
22  15.0            Chris Hogan  10/24/1987  27.0    6-1   210.0
23  55.0           Jerry Hughes   8/13/1988  26.0    6-2   254.0
24  22.0           Fred Jackson   2/20/1981  33.0    6-1   215.0
25  58.0        Randell Johnson   3/23/1991  23.0    6-3   242.0
26  71.0        Cyrus Kouandjio   7/21/1993  21.0    6-7   322.0
27  31.0           Kenny Ladler   6/23/1992  22.0    6-1   200.0
28  91.0           Manny Lawson   7/13/1984  30.0    6-5   240.0
29   3.0              EJ Manuel   3/19/1990  24.0    6-4   237.0
30  21.0        Leodis McKelvin    9/1/1985  29.0   5-11   190.0
31  18.0             Kyle Orton  11/14/1982  32.0    6-4   228.0
32  79.0             Erik Pears   6/25/1982  32.0    6-8   316.0
33  57.0              Ty Powell   4/27/1988  26.0    6-2   249.0
34  30.0          Bacarri Rambo   6/27/1990  24.0    6-1   211.0
35  68.0       Cyril Richardson  12/27/1990  24.0    6-5   329.0
36  56.0           Keith Rivers    5/5/1986  28.0    6-2   236.0
37  37.0  Nickell Robey-Coleman   1/17/1992  22.0    5-8   180.0
38  65.0       Garrison Sanborn   7/31/1985  29.0    6-1   240.0
39   6.0         Colton Schmidt  10/27/1990  24.0   5-11   224.0
40  25.0       Da'Norris Searcy  11/16/1988  26.0   5-11   205.0
41  85.0              Lee Smith  11/21/1987  27.0    6-6   265.0
42  51.0         Brandon Spikes    9/3/1987  27.0    6-3   250.0
43  28.0           C.J. Spiller    8/5/1987  27.0   5-11   194.0
44  38.0          Frank Summers    9/6/1985  29.0   5-10   240.0
45  11.0         Marcus Thigpen   5/15/1986  28.0    5-9   193.0
46  80.0        Deonte Thompson   2/14/1989  25.0    6-0   204.0
47  60.0            Kraig Urbik   9/23/1985  29.0    6-5   323.0
48  14.0          Sammy Watkins   6/14/1993  21.0    6-1   211.0
49  23.0         Aaron Williams   4/23/1990  24.0    6-0   195.0
50  74.0         Chris Williams   8/26/1985  29.0    6-6   326.0
51  27.0          Duke Williams  10/15/1990  24.0   5-11   201.0
52  95.0          Kyle Williams   6/10/1983  31.0    6-1   303.0
53  94.0         Mario Williams   1/31/1985  29.0    6-6   300.0
54  19.0          Mike Williams   5/18/1987  27.0    6-2   204.0
55  70.0              Eric Wood   3/18/1986  28.0    6-4   310.0
56  10.0           Robert Woods   4/10/1992  22.0    6-0   195.0
57  92.0            Jarius Wynn   8/29/1986  28.0    6-5   273.0
58   NaN             Team Total         NaN  26.1  6-2.1   244.9

          College/University Position  Games_Played_in_Season  \
0                Florida St.      RLB                      14
1                        LSU       DB                      14
2                 Kansas St.       RB                       7
3                 Louisville      LLB                      16
4               Northwestern       DT                      16
5                    Montana        K                      16
6                       Iowa       TE                      16
7                     Regina       DT                      16
8                       Duke       DB                       7
9                    Alabama      RDT                      15
10              Valdosta St.       LB                      13
11           Mississippi St.       RB                      16
12               Connecticut       WR                      10
13                    Centre        P                      16
14            South Carolina      RCB                      14
15                   Georgia       LT                      16
16                     Texas       WR                      10
17                  Arkansas       TE                      10
18             New Hampshire      LCB                      16
19                 Minnesota       TE                       5
20                   Clemson        T                      16
21                Miami (FL)       RT                      16
22                  Monmouth       WR                      16
23                       TCU      RDE                      16
24               Coe College       RB                      14
25          Florida Atlantic       LB                       5
26                   Alabama        T                       1
27                Vanderbilt       DB                       2
28        North Carolina St.       LB                      16
29               Florida St.       QB                       5
30                      Troy      LCB                      10
31                    Purdue       QB                      12
32              Colorado St.       RG                      16
33                   Harding       DE                      14
34                   Georgia       DB                       4
35                    Baylor        G                      12
36                       USC       LB                      12
37                       USC       DB                      16
38               Florida St.       LS                      16
39                  UC Davis        P                      16
40            North Carolina       SS                      15
41        Tennessee,Marshall       TE                      14
42                   Florida      MLB                      16
43                   Clemson       RB                       9
44                      UNLV       RB                      10
45                   Indiana       RB                       5
46                   Florida       WR                       1
47                 Wisconsin       LG                      16
48                   Clemson       WR                      16
49                     Texas       FS                      15
50                Vanderbilt        T                       3
51                    Nevada       DB                      16
52                       LSU      LDT                      15
53        North Carolina St.      LDE                      16
54                  Syracuse       WR                       9
55                Louisville        C                      16
56                       USC       WR                      16
57  Georgia Military,Georgia       DE                      11
58                       NaN      NaN                      16

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                      14.0        2.0           8.0  Bills  2014
1                       1.0        2.0           1.0  Bills  2014
2                       2.0        2.0           2.0  Bills  2014
3                      14.0        0.0           9.0  Bills  2014
4                       0.0        3.0           2.0  Bills  2014
5                       0.0        6.0           4.0  Bills  2014
6                       5.0        7.0           4.0  Bills  2014
7                       1.0        1.0           3.0  Bills  2014
8                       0.0        0.0           0.0  Bills  2014
9                      15.0        3.0          18.0  Bills  2014
10                      0.0        3.0           1.0  Bills  2014
11                      0.0        4.0           3.0  Bills  2014
12                      0.0        2.0           0.0  Bills  2014
13                      0.0        0.0           0.0  Bills  2014
14                     14.0        2.0           5.0  Bills  2014
15                     16.0        2.0           7.0  Bills  2014
16                      0.0        1.0           0.0  Bills  2014
17                      5.0        1.0           0.0  Bills  2014
18                      9.0        7.0           4.0  Bills  2014
19                      5.0        1.0           1.0  Bills  2014
20                      0.0        3.0           1.0  Bills  2014
21                     16.0        0.0           7.0  Bills  2014
22                      2.0        1.0           3.0  Bills  2014
23                     16.0        4.0          10.0  Bills  2014
24                      9.0        7.0           7.0  Bills  2014
25                      0.0        0.0           1.0  Bills  2014
26                      0.0        0.0           0.0  Bills  2014
27                      0.0        0.0           0.0  Bills  2014
28                      0.0        8.0           2.0  Bills  2014
29                      4.0        1.0           2.0  Bills  2014
30                      9.0        6.0           4.0  Bills  2014
31                     12.0        9.0           8.0  Bills  2014
32                     16.0        8.0           7.0  Bills  2014
33                      0.0        1.0           1.0  Bills  2014
34                      0.0        1.0           1.0  Bills  2014
35                      4.0        0.0           2.0  Bills  2014
36                      3.0        6.0           2.0  Bills  2014
37                      7.0        1.0           3.0  Bills  2014
38                      0.0        5.0           2.0  Bills  2014
39                      0.0        0.0           1.0  Bills  2014
40                     13.0        3.0           6.0  Bills  2014
41                     10.0        3.0           0.0  Bills  2014
42                     10.0        4.0           6.0  Bills  2014
43                      5.0        4.0           4.0  Bills  2014
44                      6.0        5.0           0.0  Bills  2014
45                      0.0        2.0           1.0  Bills  2014
46                      0.0        2.0           0.0  Bills  2014
47                      9.0        4.0           4.0  Bills  2014
48                     16.0        0.0           8.0  Bills  2014
49                     14.0        3.0           5.0  Bills  2014
50                      3.0        6.0           1.0  Bills  2014
51                      4.0        1.0           3.0  Bills  2014
52                     15.0        8.0          12.0  Bills  2014
53                     16.0        8.0          19.0  Bills  2014
54                      0.0        4.0           1.0  Bills  2014
55                     16.0        5.0           7.0  Bills  2014
56                     15.0        1.0           5.0  Bills  2014
57                      1.0        5.0           2.0  Bills  2014
58                      NaN        3.1           NaN  Bills  2014

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.         Player   BirthDate   Age Height  Weight College/University  \
0   90.0    T.J. Barnes   6/14/1990  25.0    6-6   355.0       Georgia Tech
1   53.0  Nigel Bradham    9/4/1989  26.0    6-2   241.0        Florida St.
2   33.0     Ron Brooks  10/16/1988  27.0   5-10   190.0                LSU
3   52.0  Preston Brown  10/27/1992  23.0    6-1   251.0         Louisville
4   97.0  Corbin Bryant    1/4/1988  27.0    6-4   300.0       Northwestern
..   ...            ...         ...   ...    ...     ...                ...
67  41.0    Cierre Wood   2/21/1991  24.0   5-11   213.0         Notre Dame
68  70.0      Eric Wood   3/18/1986  29.0    6-4   310.0         Louisville
69  10.0   Robert Woods   4/10/1992  23.0    6-0   195.0                USC
70  69.0   Jerel Worthy   4/28/1990  25.0    6-2   298.0       Michigan St.
71   NaN     Team Total         NaN  26.2  6-1.7   243.2                NaN

   Position  Games_Played_in_Season  Games_Started_in_Season  NFL_Years  \
0        DT                       4                      1.0        1.0
1       RLB                      11                     11.0        3.0
2        DB                      13                      0.0        3.0
3       MLB                      16                     16.0        1.0
4       LDT                      16                     10.0        4.0
..      ...                     ...                      ...        ...
67       RB                       2                      0.0        2.0
68        C                      16                     16.0        6.0
69       WR                      14                      9.0        2.0
70       DT                       2                      0.0        3.0
71      NaN                      16                      NaN        3.4

    Player_Value   Team  Year
0            1.0  Bills  2015
1            6.0  Bills  2015
2            1.0  Bills  2015
3            9.0  Bills  2015
4            6.0  Bills  2015
..           ...    ...   ...
67           0.0  Bills  2015
68          10.0  Bills  2015
69           5.0  Bills  2015
70           0.0  Bills  2015
71           NaN  Bills  2015

[72 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.             Player   BirthDate   Age Height  Weight  \
0   49.0    Bryson Albright   3/15/1994  22.0    6-5   245.0
1   57.0  Lorenzo Alexander   5/31/1983  33.0    6-1   245.0
2   33.0      Colt Anderson  10/25/1985  31.0   5-10   194.0
3   26.0     Robert Blanton    9/7/1989  27.0    6-1   208.0
4   52.0      Preston Brown  10/27/1992  24.0    6-1   251.0
..   ...                ...         ...   ...    ...     ...
64  95.0      Kyle Williams   6/10/1983  33.0    6-1   303.0
65  70.0          Eric Wood   3/18/1986  30.0    6-4   310.0
66  10.0       Robert Woods   4/10/1992  24.0    6-0   195.0
67  94.0       Jerel Worthy   4/28/1990  26.0    6-2   298.0
68   NaN         Team Total         NaN  26.6  6-1.8   243.9

   College/University Position  Games_Played_in_Season  \
0          Miami (OH)       DE                       1
1          California     ROLB                      16
2             Montana       DB                       2
3          Notre Dame       DB                      10
4          Louisville     RILB                      16
..                ...      ...                     ...
64                LSU      LDE                      15
65         Louisville        C                       9
66                USC       WR                      13
67       Michigan St.       DT                      13
68                NaN      NaN                      16

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                       0.0        0.0           0.0  Bills  2016
1                      16.0        9.0          11.0  Bills  2016
2                       0.0        6.0           0.0  Bills  2016
3                       2.0        4.0           1.0  Bills  2016
4                      16.0        2.0           7.0  Bills  2016
..                      ...        ...           ...    ...   ...
64                     15.0       10.0           9.0  Bills  2016
65                      9.0        7.0           5.0  Bills  2016
66                     10.0        3.0           6.0  Bills  2016
67                      0.0        4.0           1.0  Bills  2016
68                      NaN        3.9           NaN  Bills  2016

[69 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.             Player   BirthDate   Age Height  Weight  \
0   57.0  Lorenzo Alexander   5/31/1983  34.0    6-1   245.0
1   33.0      Colt Anderson  10/25/1985  32.0   5-10   194.0
2   22.0        Joe Banyard  11/12/1988  29.0   5-11   213.0
3   13.0    Kelvin Benjamin    2/5/1991  26.0    6-5   245.0
4   29.0     Robert Blanton    9/7/1989  28.0    6-1   208.0
..   ...                ...         ...   ...    ...     ...
61  70.0          Eric Wood   3/18/1986  31.0    6-4   310.0
62  94.0       Jerel Worthy   4/28/1990  27.0    6-2   298.0
63  20.0    Shareece Wright    4/8/1987  30.0   5-11   184.0
64  54.0    Eddie Yarbrough   4/24/1993  24.0    6-3   259.0
65   NaN         Team Total         NaN  26.8  6-1.8   245.2

   College/University Position  Games_Played_in_Season  \
0          California      LLB                      16
1             Montana       DB                       5
2       Texas-El Paso       RB                       3
3         Florida St.       WR                       6
4          Notre Dame       DB                       2
..                ...      ...                     ...
61         Louisville        C                      16
62       Michigan St.       DT                       5
63                USC      RCB                      12
64            Wyoming      LDE                      16
65                NaN      NaN                      16

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                      11.0       10.0           5.0  Bills  2017
1                       0.0        7.0           0.0  Bills  2017
2                       0.0        4.0           0.0  Bills  2017
3                       6.0        3.0           2.0  Bills  2017
4                       0.0        5.0           0.0  Bills  2017
..                      ...        ...           ...    ...   ...
61                     16.0        8.0           7.0  Bills  2017
62                      0.0        5.0           0.0  Bills  2017
63                      5.0        6.0           3.0  Bills  2017
64                      6.0        0.0           3.0  Bills  2017
65                      NaN        3.8           NaN  Bills  2017

[66 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.               Player   BirthDate   Age Height  Weight  \
0   57.0    Lorenzo Alexander   5/31/1983  35.0    6-1   245.0
1   17.0           Josh Allen   5/21/1996  22.0    6-5   237.0
2    3.0       Derek Anderson   6/15/1983  35.0    6-6   235.0
3    5.0         Matt Barkley    9/8/1990  28.0    6-2   234.0
4   13.0      Kelvin Benjamin    2/5/1991  27.0    6-5   245.0
..   ...                  ...         ...   ...    ...     ...
71  92.0  Adolphus Washington  11/24/1994  24.0    6-4   295.0
72  27.0    Tre'Davious White   1/16/1995  23.0   5-11   192.0
73  95.0        Kyle Williams   6/10/1983  35.0    6-1   303.0
74  54.0      Eddie Yarbrough   4/24/1993  25.0    6-3   259.0
75   NaN           Team Total         NaN  26.5  6-1.8   240.0

   College/University Position  Games_Played_in_Season  \
0          California      LLB                      16
1     Reedley,Wyoming       QB                      12
2          Oregon St.       QB                       2
3                 USC       QB                       1
4         Florida St.       WR                      12
..                ...      ...                     ...
71           Ohio St.       DT                       1
72                LSU      LCB                      16
73                LSU      LDT                      16
74            Wyoming       DE                      15
75                NaN      NaN                      16

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                       8.0       11.0           7.0  Bills  2018
1                      11.0        0.0           6.0  Bills  2018
2                       2.0       12.0           1.0  Bills  2018
3                       1.0        5.0           1.0  Bills  2018
4                      10.0        4.0           2.0  Bills  2018
..                      ...        ...           ...    ...   ...
71                      0.0        2.0           0.0  Bills  2018
72                     16.0        1.0           7.0  Bills  2018
73                     16.0       12.0          12.0  Bills  2018
74                      0.0        1.0           2.0  Bills  2018
75                      NaN        3.6           NaN  Bills  2018

[76 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.             Player   BirthDate   Age Height  Weight  \
0   57.0  Lorenzo Alexander   5/31/1983  36.0    6-1   245.0
1   41.0  Maurice Alexander   2/16/1991  28.0    6-2   220.0
2   17.0         Josh Allen   5/21/1996  23.0    6-5   237.0
3    5.0       Matt Barkley    9/8/1990  29.0    6-2   234.0
4   71.0         Ryan Bates   2/14/1997  22.0    6-4   302.0
5   10.0       Cole Beasley   4/26/1989  30.0    5-8   174.0
6   65.0       Ike Boettger   10/5/1994  25.0    6-6   313.0
7    9.0    Corey Bojorquez   9/13/1996  23.0    6-0   217.0
8   15.0         John Brown    4/3/1990  29.0   5-11   178.0
9   28.0       Kurt Coleman    7/1/1988  31.0   5-11   208.0
10  73.0       Dion Dawkins   4/26/1994  25.0    6-5   320.0
11  42.0    Patrick DiMarco   4/30/1989  30.0    6-1   234.0
12  49.0   Tremaine Edmunds    5/2/1998  21.0    6-5   250.0
13  76.0      Jon Feliciano   2/10/1992  27.0    6-4   325.0
14  69.0      Reid Ferguson   3/24/1994  25.0    6-2   235.0
15  70.0          Cody Ford  12/28/1996  23.0    6-3   329.0
16  16.0      Robert Foster    5/7/1994  25.0    6-2   196.0
17  20.0         Frank Gore   5/14/1983  36.0    5-9   212.0
18   4.0   Stephen Hauschka   6/29/1985  34.0    6-4   210.0
19  55.0       Jerry Hughes   8/13/1988  31.0    6-2   254.0
20  23.0         Micah Hyde  12/31/1990  29.0    6-0   197.0
21  92.0     Darryl Johnson    4/4/1997  22.0    6-6   250.0
22  46.0     Jaquan Johnson  11/13/1995  24.0   5-10   191.0
23  29.0      Kevin Johnson    8/5/1992  27.0    6-0   185.0
24  24.0      Taron Johnson   7/27/1996  23.0   5-11   192.0
25  11.0          Zay Jones   3/30/1995  24.0    6-2   200.0
26  88.0        Dawson Knox  11/14/1996  23.0    6-4   254.0
27  81.0        Tyler Kroft  10/15/1992  27.0    6-6   252.0
28  90.0        Shaq Lawson   6/17/1994  25.0    6-3   265.0
29  94.0       Corey Liuget   3/18/1990  29.0    6-2   300.0
30  61.0       Spencer Long   11/8/1990  29.0    6-5   318.0
31  98.0     Star Lotulelei  12/20/1989  30.0    6-2   315.0
32  31.0       Dean Marlowe   7/25/1992  27.0    6-1   205.0
33  19.0    Isaiah McKenzie    4/9/1995  24.0    5-8   173.0
34  58.0        Matt Milano   7/28/1994  25.0    6-0   223.0
35  60.0        Mitch Morse   4/21/1992  27.0    6-6   305.0
36  93.0       Trent Murphy  12/22/1990  29.0    6-6   260.0
37  33.0         Siran Neal    8/4/1994  25.0    6-0   206.0
38  77.0          Ty Nsekhe  10/27/1985  34.0    6-8   325.0
39  91.0          Ed Oliver  12/12/1997  22.0    6-1   287.0
40  94.0          Kyle Peko   7/23/1993  26.0    6-1   305.0
41  32.0     Senorise Perry   9/19/1991  28.0    6-0   210.0
42  99.0  Harrison Phillips   1/25/1996  23.0    6-3   307.0
43  97.0    Jordan Phillips   9/21/1992  27.0    6-6   341.0
44  21.0       Jordan Poyer   4/25/1991  28.0    6-0   191.0
45  18.0      Andre Roberts    1/9/1988  31.0   5-11   195.0
46  26.0   Devin Singletary    9/3/1997  22.0    5-7   203.0
47  85.0          Lee Smith  11/21/1987  32.0    6-6   265.0
48  67.0      Quinton Spain    8/7/1991  28.0    6-4   330.0
49  51.0    Julian Stanford    9/2/1990  29.0    6-1   230.0
50  89.0      Tommy Sweeney    7/1/1995  24.0    6-5   255.0
51  96.0     Vincent Taylor    1/5/1994  25.0    6-3   311.0
52  52.0     Corey Thompson  12/23/1993  26.0    6-1   222.0
53  39.0       Levi Wallace   6/12/1995  24.0    6-0   179.0
54  27.0  Tre'Davious White   1/16/1995  24.0   5-11   192.0
55  82.0      Duke Williams   5/13/1992  27.0    6-3   225.0
56  22.0        T.J. Yeldon   10/2/1993  26.0    6-1   223.0
57   NaN         Team Total         NaN  26.8  6-1.9   245.3

                  College/University Position  Games_Played_in_Season  \
0                         California      RLB                      16
1                           Utah St.       DB                       7
2                    Reedley,Wyoming       QB                      16
3                                USC       QB                       2
4                           Penn St.        G                       8
5                                SMU       WR                      15
6                               Iowa        T                       2
7           Cerritos (CA),New Mexico        P                      16
8                      Pittsburg St.       WR                      15
9                           Ohio St.       DB                      14
10                            Temple       LT                      16
11                    South Carolina       FB                      16
12                     Virginia Tech      MLB                      16
13                        Miami (FL)       RG                      16
14                               LSU       LS                      16
15                          Oklahoma       RT                      16
16                           Alabama       WR                      13
17                        Miami (FL)       RB                      16
18     Middlebury,North Carolina St.        K                      16
19                               TCU      RDE                      16
20                              Iowa       FS                      16
21                North Carolina A&T       DE                      16
22                        Miami (FL)       DB                      13
23                       Wake Forest       DB                      16
24                         Weber St.       DB                      12
25                     East Carolina       WR                       5
26                       Mississippi       TE                      15
27                           Rutgers       TE                      11
28                           Clemson       DE                      15
29                          Illinois       DT                       7
30                          Nebraska        G                      14
31            Snow College (UT),Utah      RDT                      16
32                     James Madison       DB                       9
33                           Georgia       WR                      15
34                       Boston Col.      LLB                      15
35                          Missouri        C                      16
36                          Stanford      LDE                      16
37                  Jacksonville St.       DB                      15
38                         Texas St.        T                      10
39                           Houston      RDT                      16
40                        Oregon St.       DT                       4
41                        Louisville       RB                      11
42                          Stanford       DT                       3
43                          Oklahoma      LDT                      16
44                        Oregon St.       SS                      16
45                       The Citadel       WR                      13
46                  Florida Atlantic       RB                      12
47                Tennessee,Marshall       WR                      16
48                     West Virginia       LG                      16
49                            Wagner       LB                      16
50                       Boston Col.       TE                       6
51                      Oklahoma St.       DT                       3
52                               LSU       LB                      12
53                           Alabama  LCB/RCB                      16
54                               LSU  RCB/LCB                      15
55  Mississippi Gulf Coast CC,Auburn       WR                       4
56                           Alabama       RB                       6
57                               NaN      NaN                      16

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                       7.0       12.0           6.0  Bills  2019
1                       0.0        5.0           1.0  Bills  2019
2                      16.0        1.0          11.0  Bills  2019
3                       0.0        6.0           1.0  Bills  2019
4                       0.0        0.0           1.0  Bills  2019
5                      10.0        7.0           6.0  Bills  2019
6                       0.0        1.0           0.0  Bills  2019
7                       0.0        1.0           1.0  Bills  2019
8                      15.0        5.0           9.0  Bills  2019
9                       0.0        9.0           1.0  Bills  2019
10                     16.0        2.0           7.0  Bills  2019
11                      4.0        7.0           0.0  Bills  2019
12                     16.0        1.0          14.0  Bills  2019
13                     16.0        4.0           7.0  Bills  2019
14                      0.0        2.0           1.0  Bills  2019
15                     15.0        0.0           6.0  Bills  2019
16                      2.0        1.0           1.0  Bills  2019
17                      8.0       14.0           4.0  Bills  2019
18                      0.0       11.0           3.0  Bills  2019
19                     16.0        9.0          10.0  Bills  2019
20                     16.0        6.0           8.0  Bills  2019
21                      0.0        0.0           2.0  Bills  2019
22                      0.0        0.0           1.0  Bills  2019
23                      1.0        4.0           2.0  Bills  2019
24                      7.0        1.0           3.0  Bills  2019
25                      2.0        2.0           1.0  Bills  2019
26                     11.0        0.0           3.0  Bills  2019
27                      3.0        4.0           1.0  Bills  2019
28                      0.0        3.0           3.0  Bills  2019
29                      0.0        8.0           1.0  Bills  2019
30                      0.0        5.0           1.0  Bills  2019
31                     16.0        6.0          10.0  Bills  2019
32                      2.0        4.0           1.0  Bills  2019
33                      8.0        2.0           2.0  Bills  2019
34                     15.0        2.0          10.0  Bills  2019
35                     16.0        4.0           7.0  Bills  2019
36                     16.0        5.0          12.0  Bills  2019
37                      1.0        1.0           1.0  Bills  2019
38                      1.0        7.0           1.0  Bills  2019
39                      7.0        0.0           6.0  Bills  2019
40                      0.0        3.0           0.0  Bills  2019
41                      0.0        5.0           0.0  Bills  2019
42                      0.0        1.0           0.0  Bills  2019
43                      9.0        4.0           8.0  Bills  2019
44                     16.0        6.0           8.0  Bills  2019
45                      0.0        9.0           0.0  Bills  2019
46                      8.0        0.0           6.0  Bills  2019
47                      5.0        8.0           0.0  Bills  2019
48                     16.0        4.0           7.0  Bills  2019
49                      0.0        7.0           2.0  Bills  2019
50                      1.0        0.0           1.0  Bills  2019
51                      0.0        2.0           1.0  Bills  2019
52                      0.0        1.0           1.0  Bills  2019
53                     16.0        1.0           7.0  Bills  2019
54                     15.0        2.0          19.0  Bills  2019
55                      3.0        0.0           1.0  Bills  2019
56                      0.0        4.0           1.0  Bills  2019
57                      NaN        3.8           NaN  Bills  2019

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.         Player   BirthDate   Age Height  Weight College/University  \
0   97.0  Mario Addison    9/6/1987  33.0    6-3   260.0               Troy
1   17.0     Josh Allen   5/21/1996  24.0    6-5   237.0    Reedley,Wyoming
2    5.0   Matt Barkley    9/8/1990  30.0    6-2   234.0                USC
3    2.0     Tyler Bass   2/14/1997  23.0   5-10   183.0   Georgia Southern
4   71.0     Ryan Bates   2/14/1997  23.0    6-4   302.0           Penn St.
..   ...            ...         ...   ...    ...     ...                ...
65  66.0  Brian Winters   7/16/1991  29.0    6-4   320.0           Kent St.
66  37.0   Daryl Worley   2/22/1995  25.0    6-1   210.0      West Virginia
67  22.0    T.J. Yeldon   10/2/1993  27.0    6-1   223.0            Alabama
68  61.0  Justin Zimmer  10/23/1992  28.0    6-3   300.0         Ferris St.
69   NaN     Team Total         NaN  26.6  6-1.9   243.1                NaN

   Position  Games_Played_in_Season  Games_Started_in_Season  NFL_Years  \
0       RDE                      15                      7.0        9.0
1        QB                      16                     16.0        2.0
2        QB                       5                      0.0        7.0
3         K                      16                      0.0        0.0
4         G                      16                      0.0        1.0
..      ...                     ...                      ...        ...
65       RG                      16                      9.0        7.0
66       DB                       1                      0.0        4.0
67       RB                       3                      0.0        5.0
68       DT                      12                      0.0        2.0
69      NaN                      16                      NaN        3.4

    Player_Value   Team  Year
0            4.0  Bills  2020
1           18.0  Bills  2020
2            1.0  Bills  2020
3            3.0  Bills  2020
4            1.0  Bills  2020
..           ...    ...   ...
65           5.0  Bills  2020
66           0.0  Bills  2020
67           1.0  Bills  2020
68           1.0  Bills  2020
69           NaN  Bills  2020

[70 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.             Player   BirthDate   Age Height  Weight  \
0   97.0      Mario Addison    9/6/1987  34.0    6-3   260.0
1   17.0         Josh Allen   5/21/1996  25.0    6-5   237.0
2   51.0          Eli Ankou    6/8/1994  27.0    6-3   325.0
3   96.0      Boogie Basham  12/16/1997  24.0    6-3   274.0
4    2.0         Tyler Bass   2/14/1997  24.0   5-10   183.0
..   ...                ...         ...   ...    ...     ...
59   7.0         Davis Webb   1/22/1995  26.0    6-5   225.0
60  27.0  Tre'Davious White   1/16/1995  26.0   5-11   192.0
61  75.0     Daryl Williams   8/31/1992  29.0    6-6   330.0
62  61.0      Justin Zimmer  10/23/1992  29.0    6-3   300.0
63   NaN         Team Total         NaN  26.5  6-1.9   244.9

   College/University Position  Games_Played_in_Season  \
0                Troy       DE                      17
1     Reedley,Wyoming       QB                      17
2                UCLA       DT                       5
3         Wake Forest       DE                       8
4    Georgia Southern        K                      17
..                ...      ...                     ...
59         California       QB                       1
60                LSU      LCB                      11
61           Oklahoma    RG/RT                      17
62         Ferris St.       DT                       6
63                NaN      NaN                      17

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                       0.0       10.0           2.0  Bills  2021
1                      17.0        3.0          19.0  Bills  2021
2                       0.0        4.0           1.0  Bills  2021
3                       0.0        0.0           1.0  Bills  2021
4                       0.0        1.0           3.0  Bills  2021
..                      ...        ...           ...    ...   ...
59                      0.0        0.0           0.0  Bills  2021
60                     11.0        4.0           4.0  Bills  2021
61                     17.0        6.0          10.0  Bills  2021
62                      0.0        3.0           1.0  Bills  2021
63                      NaN        3.6           NaN  Bills  2021

[64 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.             Player   BirthDate   Age Height  Weight  \
0   17.0         Josh Allen   5/21/1996  26.0    6-5   237.0
1   51.0          Eli Ankou    6/8/1994  28.0    6-3   325.0
2   55.0      Boogie Basham  12/16/1997  25.0    6-3   274.0
3    2.0         Tyler Bass   2/14/1997  25.0   5-10   183.0
4   71.0         Ryan Bates   2/14/1997  25.0    6-4   302.0
..   ...                ...         ...   ...    ...     ...
70  54.0     Baylon Spector  10/20/1998  24.0    6-0   233.0
71  89.0      Tommy Sweeney    7/1/1995  27.0    6-5   255.0
72  64.0     Greg Van Roten   2/26/1990  32.0    6-3   305.0
73  27.0  Tre'Davious White   1/16/1995  27.0   5-11   192.0
74   NaN         Team Total         NaN  27.2  6-1.7   241.1

   College/University Position  Games_Played_in_Season  \
0     Reedley,Wyoming       QB                      16
1                UCLA       DT                       0
2         Wake Forest       DE                      15
3    Georgia Southern        K                      16
4            Penn St.       RG                      15
..                ...      ...                     ...
70            Clemson       LB                       6
71        Boston Col.       TE                       5
72       Pennsylvania        G                      16
73                LSU      RCB                       6
74                NaN      NaN                      16

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                      16.0        4.0          20.0  Bills  2022
1                       0.0        5.0           0.0  Bills  2022
2                       0.0        1.0           2.0  Bills  2022
3                       0.0        2.0           3.0  Bills  2022
4                      15.0        3.0           8.0  Bills  2022
..                      ...        ...           ...    ...   ...
70                      0.0        0.0           1.0  Bills  2022
71                      0.0        3.0           0.0  Bills  2022
72                      4.0       10.0           3.0  Bills  2022
73                      6.0        5.0           2.0  Bills  2022
74                      NaN        4.3           NaN  Bills  2022

[75 rows x 14 columns]

C:\Users\Family\AppData\Local\Temp\ipykernel_14236\3057426242.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(html_roster_children_li[4])[0]

     No.             Player  BirthDate   Age Height  Weight  \
0   17.0         Josh Allen  5/21/1996  27.0    6-5   237.0
1    9.0         Kyle Allen   3/8/1996  27.0    6-3   210.0
2    2.0         Tyler Bass  2/14/1997  26.0   5-10   183.0
3   71.0         Ryan Bates  2/14/1997  26.0    6-4   302.0
4   47.0  Christian Benford  9/21/2000  23.0    6-1   205.0
..   ...                ...        ...   ...    ...     ...
58  74.0    Ryan Van Demark  3/22/1998  25.0    6-6   307.0
59  93.0     Kendal Vickers  5/23/1995  28.0    6-3   295.0
60  27.0  Tre'Davious White  1/16/1995  28.0   5-11   192.0
61  42.0    Dorian Williams   6/8/2001  22.0    NaN   230.0
62   NaN         Team Total        NaN  27.4  6-1.7   240.7

   College/University Position  Games_Played_in_Season  \
0     Reedley,Wyoming       QB                      17
1   Texas A&M,Houston       QB                       7
2    Georgia Southern        K                      17
3            Penn St.        G                      17
4           Villanova       CB                      15
..                ...      ...                     ...
58        Connecticut        T                      12
59          Tennessee       DE                       2
60                LSU       CB                       4
61             Tulane       LB                      17
62                NaN      NaN                      17

    Games_Started_in_Season  NFL_Years  Player_Value   Team  Year
0                      17.0        5.0          18.0  Bills  2023
1                       0.0        5.0           0.0  Bills  2023
2                       0.0        3.0           3.0  Bills  2023
3                       0.0        4.0           1.0  Bills  2023
4                      14.0        1.0           5.0  Bills  2023
..                      ...        ...           ...    ...   ...
58                      0.0        0.0           1.0  Bills  2023
59                      0.0        3.0           0.0  Bills  2023
60                      4.0        6.0           2.0  Bills  2023
61                      2.0        0.0           2.0  Bills  2023
62                      NaN        4.6           NaN  Bills  2023

[63 rows x 14 columns]

In [8]:
stop

NameError: name 'stop' is not defined

In [ ]:
roster_team_year_li = create_roster_csv(years=years)

In [ ]:
roster_team_year_li

# 2023 Rosters

In [ ]:
# use this function before creating tables
def roster_df_2023(url:str):
    
    html = requests.get(url).text
    
    soup = bs(html, 'html.parser')

    table = soup.find_all(class_='table_wrapper')[0]

    str_table = str(table)

    start_num_str_comment_tag = str_table.find('<!--')+4

    table_html = bs(str_table[start_num_str_comment_tag:], 'html.parser')

    df = pd.read_html(str(table_html), index_col=1)[0]
    
    time.sleep(random.randrange(5,8))
    return df

In [ ]:
def create_roster_csv(years:None):
    
    years = years
    
    team_to_url_df = pd.DataFrame(
        data=[
            [
                'crd', #Cardinals
                'atl', #Falcons
                'rav', #Ravens
                'buf', #Bills
                'car', #Panthers
                'chi', #Bears
                'cin', #Bengals
                'cle', #Browns
                'dal', #Cowboys
                'den', #Broncos
                'det', #Lions
                'gnb', #Packers
                'htx', #Texans
                'clt', # Colts
                'jax', #Jaguars
                'kan', #Chiefs
                'rai', #Raiders
                'sdg', #Chargers
                'ram', #Rams
                'mia', #Dolphins
                'min', #Vikings
                'nwe', #Patriots
                'nor', #Saints
                'nyg', #Giants
                'nyj', #Jets
                'phi', #Eagles
                'pit', #Steelers
                'sfo', #49ers
                'sea', #Seahawks
                'tam', #Buccaneers
                'oti', #Titans
                'was' #Commanders
            ]
        ], 
        columns=[
            'Cardinals',
            'Falcons',
            'Ravens',
            'Bills',
            'Panthers',
            'Bears',
            'Bengals',
            'Browns',
            'Cowboys',
            'Broncos',
            'Lions',
            'Packers',
            'Texans',
            'Colts',
            'Jaguars',
            'Chiefs',
            'Raiders',
            'Chargers',
            'Rams',
            'Dolphins',
            'Vikings',
            'Patriots',
            'Saints',
            'Giants',
            'Jets',
            'Eagles',
            'Steelers',
            '49ers',
            'Seahawks',
            'Buccaneers',
            'Titans',
            'Commanders'
        ])
    # format team_to_url_df list to choose team, the second bracket is for the year
    roster_url = 'http://www.pro-football-reference.com/teams/{}/{}_roster.htm'
    
    #to observe imported df
    roster_team_year_li = []
    
    for year in years:
        for team_url in team_to_url_df:
            
            #webscrape roster dataframe
            url = roster_url.format(team_to_url_df[team_url].values[0], year)
            df = roster_df_2023(url=url)
            
            #drop last col
            df.drop(columns=['Drafted (tm/rnd/yr)'], axis=1)
                        
            df.insert(1, 'Team', team_url)
            
            #where to save datafram
            df.to_csv('NFL_Data_{}\\'.format(year) + team_url + '\\{}_roster'.format(team_url))
           
            #to observe imported df
            roster_team_year_li.append(df)
            
    return roster_team_year_li

In [ ]:
roster_team_year_li = create_roster_csv(years=[2023])